parameters:
  - name: url
  - name: username
  - name: password
  - name: classpath
  - name: changeLogFile
    default: 'master-changelog.xml'
  - name: liquibaseSchemaName
  - name: defaultSchemaName
  - name: logLevel
    default: 'debug'
  - name: schema
  - name: title
  - name: liquibaseTablespaceName
  - name: databaseChangelogLockTableName
  - name: databaseChangelogTableName
  - name: version
  - name: azureSubscription
  - name: KeyVaultName
  - name: contexts

steps:

  - script: |
      apt-get update
      apt-get -y install wget
      wget -h
      cd $(Pipeline.Workspace)
      mkdir java-11
      cd java-11
      wget -c https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz
    displayName: "Download JAVA 11"

  - task: AzureKeyVault@2
    inputs:
      azureSubscription: ${{ parameters.azureSubscription }}
      KeyVaultName: ${{ parameters.KeyVaultName }}
      SecretsFilter: '*'
      RunAsPreJob: false

  - task: JavaToolInstaller@0
    inputs:
      versionSpec: "11"
      jdkArchitectureOption: x64
      jdkSourceOption: LocalDirectory
      jdkFile: "$(Pipeline.Workspace)/java-11/openjdk-11.0.2_linux-x64_bin.tar.gz"
      jdkDestinationDirectory: "$(Pipeline.Workspace)/java-11/extract"
      cleanDestinationDirectory: true
    displayName: "Installing JAVA 11"

  - script: |
      cd $(Pipeline.Workspace)
      mkdir liquibase-app
      wget -c https://github.com/liquibase/liquibase/releases/download/v4.8.0/liquibase-4.8.0.tar.gz
      tar -xzf liquibase-4.8.0.tar.gz -C liquibase-app
      rm -rf liquibase-4.8.0.tar.gz
      echo "##vso[task.prependpath]$(Pipeline.Workspace)/liquibase-app"
    displayName: "Install Liquibase"

  - template: ../templates/clean_and_download.yml
    parameters:
      artifact: ${{ parameters.version }}-liquibase-script

  - script: |
      liquibase \
        --driver=oracle.jdbc.driver.OracleDriver \
        --url="${{ parameters.url }}" \
        --username="${{ parameters.username }}" \
        --password=${{ parameters.password }} \
        --classpath=${{ parameters.classpath }} \
        --changeLogFile=${{ parameters.changeLogFile }} \
        --liquibaseSchemaName=${{ parameters.liquibaseSchemaName }} \
        --defaultSchemaName=${{ parameters.defaultSchemaName }} \
        --contexts=${{ parameters.contexts }} \
        --log-level=${{ parameters.logLevel }} \
        --liquibase-tablespace-name=${{ parameters.liquibaseTablespaceName }} \
        --database-changelog-lock-table-name=${{ parameters.databaseChangelogLockTableName }} \
        --database-changelog-table-name=${{ parameters.databaseChangelogTableName }} \
        rollback ${{ parameters.version }}
    displayName: ${{ parameters.title }}