parameters:
  - name: dependsOn
    type: object
    default: []
  - name: version
  - name: poolName
  - name: azureSubscription
  - name: KeyVaultName

jobs:
  - job: upgrade_db
    displayName: "Upgrade DB"
    pool:
      name: ${{ parameters.poolName }}
    ${{ if parameters.dependsOn }}:
      dependsOn: ${{ parameters.dependsOn }}
    condition: succeeded()
    steps:
      - checkout: none

      - script: echo ${{ parameters.version }}
        displayName: Branch Version

      - script: |
          apt-get update
          apt-get -y install wget
          wget -h
          cd $(Pipeline.Workspace)
          mkdir java-11
          cd java-11
          wget -c https://download.java.net/java/GA/jdk11/9/GPL/openjdk-11.0.2_linux-x64_bin.tar.gz
        displayName: "Download JAVA 11"

      - task: AzureKeyVault@2
        inputs:
          azureSubscription: ${{ parameters.azureSubscription }}
          KeyVaultName: ${{ parameters.KeyVaultName }}
          SecretsFilter: '*'
          RunAsPreJob: false

      - task: JavaToolInstaller@0
        inputs:
          versionSpec: "11"
          jdkArchitectureOption: x64
          jdkSourceOption: LocalDirectory
          jdkFile: "$(Pipeline.Workspace)/java-11/openjdk-11.0.2_linux-x64_bin.tar.gz"
          jdkDestinationDirectory: "$(Pipeline.Workspace)/java-11/extract"
          cleanDestinationDirectory: true
        displayName: "Installing JAVA 11"

      - script: |
          cd $(Pipeline.Workspace)
          mkdir liquibase-app
          wget -c https://github.com/liquibase/liquibase/releases/download/v4.8.0/liquibase-4.8.0.tar.gz
          tar -xzf liquibase-4.8.0.tar.gz -C liquibase-app
          rm -rf liquibase-4.8.0.tar.gz
          echo "##vso[task.prependpath]$(Pipeline.Workspace)/liquibase-app"
        displayName: "Install Liquibase"

      - template: ./clean_and_download.yml
        parameters:
          artifact: ${{ parameters.version }}-liquibase-script

      # PGS
      - template: ../templates/liquibase-update.yml
        parameters:
          url: $(sit-db-agid-url-simple)
          username: $(sit-db-agid-username)
          password: $(sit-db-agid-password)
          classpath: $(Pipeline.Workspace)/${{ parameters.version }}-liquibase-script/changelogs/payment-transaction-gateway
          liquibaseSchemaName: $(sit-db-agid-schema)
          defaultSchemaName: $(sit-db-agid-schema)
          schema: $(sit-db-agid-schema)
          args: "-Dversion=${{ parameters.version }}"
          liquibaseTablespaceName: $(sit-db-agid-tablespace)
          title: "Update DB PGS"
          databaseChangelogLockTableName: "DATABASECHANGELOGLOCK_PGS"
          databaseChangelogTableName: "DATABASECHANGELOG_PGS"
          contexts: "tag,baseline,incremental"