version: "3.9"

services:
 
  pagopa-payment-transactions-gateway:
    container_name: pagopa-payment-transactions-gateway
    env_file: .env
    build:
      context: .
    ports:
        - "8080:8080"
    networks:
      - payment-gateway-net

  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - payment-gateway-net
    
  postgres-liquibase:
    container_name: lobo-liquibase
    image: liquibase/liquibase
    command: --url=jdbc:postgresql://lobo-db:5432/postgres?user=postgres&password=postgres --changeLogFile=changelog.xml update
    volumes:
      - ./config/changelog.xml:/liquibase/changelog.xml
      - ./scripts:/liquibase/scripts
    networks:
      - payment-gateway-net

networks:
  payment-gateway-net:
    name: payment-gateway-net
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1450