INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'bancomatPay.client.group.code', 'groupCode', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'bancomatPay.client.institute.code', 'instituteCode', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'bancomatPay.client.tag', 'tag', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'bancomatPay.client.token', 'token', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'bancomatPay.client.url', 'http://bancomatPay:7954/bpay', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'bancomatPay.client.timeout.ms', '5000', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'azureAuth.client.postepay.enabled', 'false', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'azureAuth.client.maxTotal', '1000', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'azureAuth.client.maxPerRoute', '1000', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'azureAuth.client.timeout.ms', '5000', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'azureAuth.client.postepay.url', 'https://postepay.auth.url.com', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'azureAuth.client.postepay.scope', 'placeholder', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'azureAuth.client.postepay.client_id', 'placeholder', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'azureAuth.client.postepay.client_secret', 'placeholder', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'postepay.client.url', 'http://bancomatPay:7954/postepay', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'postepay.client.timeout.ms', '5000', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'postepay.notificationURL', 'http://bancomatPay:7954/payment-transactions-gateway/v1/request-payments/postepay', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'postepay.clientId.APP.config', 'merchant_id_app|shop_id_app|APP|IMMEDIATA|', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'postepay.clientId.WEB.config', 'merchant_id_web|shop_id_web|WEB|IMMEDIATA|http://mocks:8081/pmmockserviceapi/home', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'postepay.logo.url', 'v1/assets/img/postepay/postepay.png', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'postepay.pgs.response.urlredirect', 'https://urlRedirect?requestId=%s&amp;scope=%s', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'postepay.pgs.response.clientResponseUrl.onboarding', 'http://localhost:8080/pp-restapi-CD/v3/webview/postepay/onboarding/continue', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'postepay.pgs.response.APP.clientResponseUrl.payment', 'http://localhost:8080/pp-restapi-CD/v3/webview/transactions/pay', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'postepay.pgs.response.WEB.clientResponseUrl.payment', 'http://localhost:8080/to_be_defined', SYSDATE);
