INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'bancomatPay.client.group.code', '', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'bancomatPay.client.institute.code', '', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'bancomatPay.client.tag', '', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'bancomatPay.client.token', '', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'bancomatPay.client.url', '', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'bancomatPay.client.timeout.ms', '', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'azureAuth.client.postepay.enabled', '', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'azureAuth.client.maxTotal', '', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'azureAuth.client.maxPerRoute', '', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'azureAuth.client.timeout.ms', '', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'azureAuth.client.postepay.url', '', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'azureAuth.client.postepay.scope', '', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'azureAuth.client.postepay.client_id', '', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'azureAuth.client.postepay.client_secret', '', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'postepay.client.url', '', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'postepay.client.timeout.ms', '', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'postepay.notificationURL', '', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'postepay.clientId.APP.config', '', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'postepay.clientId.WEB.config', '', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'postepay.logo.url', '', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'postepay.pgs.response.urlredirect', '', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'postepay.pgs.response.clientResponseUrl.onboarding', '', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'postepay.pgs.response.APP.clientResponseUrl.payment', '', SYSDATE);

INSERT INTO PP_PGS_CONFIG (ID_CONFIG, CONFIG_KEY, CONFIG_VALUE, LAST_UPDATE_DATE)
VALUES(SEQ_PGS_CONFIG.NEXTVAL, 'postepay.pgs.response.WEB.clientResponseUrl.payment', '', SYSDATE);
