# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger: none
pr: none

parameters:
  - name: 'buildVersion'
    displayName: 'Build Version'
    type: string

variables:
  vmImageNameDefault: 'ubuntu-latest'
  poolName: 'pm-agent-pool-uat'
  azureSubscription: 'Pm-Subscription-uat'
  KeyVaultName: 'u87-kmn-pm-uat-pci'
  definitionId: 113

stages:

  - stage: stage_check_prerequisites
    displayName: Check Prerequisites
    pool:
      vmImage: $(vmImageNameDefault)
    jobs:
      - job: job_check_version
        displayName: Check Version
        steps:
          - template: 'templates/verify-branch-version.yml'
            parameters:
              buildVersion: '${{parameters.buildVersion}}'
          - script: echo '${{parameters.buildVersion}}'
            displayName: Branch Version

  - stage: stage_deploy_UAT_liquibase
    displayName: Execute Deploy UAT - Liquibase
    dependsOn:
      - stage_check_prerequisites
    condition: succeeded('stage_check_prerequisites')
    jobs:
      - template: templates/uat/upgrade_db.yml
        parameters:
          version: ${{ parameters.buildVersion }}
          poolName: $(poolName)
          azureSubscription: $(azureSubscription)
          KeyVaultName: $(KeyVaultName)
          definitionId: $(definitionId)

  - stage: stage_deploy_UAT
    displayName: Execute Deploy UAT
    dependsOn:
      - stage_deploy_UAT_liquibase
    condition: and(succeeded('stage_check_prerequisites'), succeeded('stage_deploy_UAT_liquibase'))
    pool:
      name: $(poolName)
    jobs:
      - deployment: deploy_UAT
        displayName: Deploy UAT
        environment: 'UAT'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadPipelineArtifact@2
                  displayName: Download Artifact
                  inputs:
                    source: 'specific'
                    project: 'PaymentManager'
                    pipeline: $(definitionId)
                    runVersion: 'latestFromBranch'
                    runBranch: 'refs/heads/releases/${{parameters.buildVersion}}'
                    allowPartiallySucceededBuilds: true
                    artifact: 'Build PTG ${{parameters.buildVersion}}'
                    path: '$(Pipeline.Workspace)'
                - template: 'templates/check-files.yml'
                  parameters:
                    buildVersion: '${{parameters.buildVersion}}'
                - task: AzureKeyVault@2
                  inputs:
                    azureSubscription: $(azureSubscription)
                    KeyVaultName: $(KeyVaultName)
                    SecretsFilter: '*'
                    RunAsPreJob: false
                - template: 'templates/deploy-artifact-on-azure-appservice.yml'
                  parameters:
                    moduleName: 'PTG'
                    artifactType: 'WAR'
                    azureSubscription: $(azureSubscription)
                    webAppName: '$(payment-gateway-appsrv-uat)'
                    workingDir: '$(Pipeline.Workspace)'
                    fileName: 'pagopa-payment-transactions-gateway-${{parameters.buildVersion}}.war'
                    deployToSlotOrASE: true
                    resourceGroupName: U87-PM-AppServices-pci-uat
                    slotName: release
                - task: PublishPipelineArtifact@1
                  displayName: Publish Artifact
                  inputs:
                    targetPath: '$(Pipeline.Workspace)/pagopa-payment-transactions-gateway-${{parameters.buildVersion}}.war'
                    artifactName: 'UAT - Deployed PTG ${{parameters.buildVersion}}'