trigger: none
pr: none

parameters:
  - name: 'buildVersion'
    displayName: 'Build Version'
    type: string

variables:
  vmImageNameDefault: 'ubuntu-latest'
  poolName: 'pm-agent-pool-prod'
  azureSubscription: 'U87-PAGOPA-PCI'
  KeyVaultName: 'U87-KMN-PM-pci-prod'
  definitionId: 134

stages:

  - stage: stage_check_prerequisites
    displayName: Check Prerequisites
    pool:
      vmImage: $(vmImageNameDefault)
    jobs:
      - job: job_check_version
        displayName: Check Version
        steps:
          - template: 'templates/verify-branch-version.yml'
            parameters:
              buildVersion: '${{parameters.buildVersion}}'
          - script: echo '${{parameters.buildVersion}}'
            displayName: Branch Version

  - stage: stage_deploy_PROD_liquibase
    displayName: Execute Deploy PROD - Liquibase
    dependsOn:
      - stage_check_prerequisites
    condition: succeeded('stage_check_prerequisites')
    jobs:
      - template: templates/prod/upgrade_db.yml
        parameters:
          version: ${{ parameters.buildVersion }}
          poolName: $(poolName)
          azureSubscription: $(azureSubscription)
          KeyVaultName: $(KeyVaultName)
          definitionId: $(definitionId)

  - stage: stage_deploy_PROD
    displayName: Execute Deploy PROD
    dependsOn:
      - stage_deploy_PROD_liquibase
    condition: and(succeeded('stage_check_prerequisites'), succeeded('stage_deploy_PROD_liquibase'))
    pool:
      name: $(poolName)
    jobs:
      - deployment: deploy_PROD
        displayName: Deploy PROD
        environment: 'PROD'
        strategy:
          runOnce:
            deploy:
              steps:
                - task: DownloadPipelineArtifact@2
                  displayName: Download Artifact
                  inputs:
                    source: 'specific'
                    project: 'PaymentManager'
                    pipeline: $(definitionId)
                    runVersion: 'latestFromBranch'
                    runBranch: 'refs/heads/releases/${{parameters.buildVersion}}'
                    allowPartiallySucceededBuilds: true
                    artifact: 'UAT - Deployed PTG ${{parameters.buildVersion}}'
                    path: '$(Pipeline.Workspace)'
                - template: 'templates/check-files.yml'
                  parameters:
                    buildVersion: '${{parameters.buildVersion}}'
                - task: AzureKeyVault@2
                  inputs:
                    azureSubscription: $(azureSubscription)
                    KeyVaultName: $(KeyVaultName)
                    SecretsFilter: '*'
                    RunAsPreJob: false
                - template: 'templates/deploy-artifact-on-azure-appservice.yml'
                  parameters:
                    moduleName: 'PTG'
                    artifactType: 'WAR'
                    azureSubscription: $(azureSubscription)
                    webAppName: '$(payment-gateway-appsrv-prod)'
                    workingDir: '$(Pipeline.Workspace)'
                    fileName: 'pagopa-payment-transactions-gateway-${{parameters.buildVersion}}.war'
                    deployToSlotOrASE: true
                    resourceGroupName: U87-PM-AppServices-pci-prod
                    slotName: release
                - task: PublishBuildArtifacts@1
                  displayName: Publish Artifact
                  inputs:
                    pathToPublish: '$(Pipeline.Workspace)/pagopa-payment-transactions-gateway-${{parameters.buildVersion}}.war'
                    artifactName: 'PROD - Deployed PTG ${{parameters.buildVersion}}'