CREATE SEQUENCE SEQ_BPAY_PAYMENT_RESPONSE 
CACHE 20000 NOORDER NOCYCLE;
CREATE TABLE PP_BPAY_PAYMENT_RESPONSE 
 (	ID NUMBER(9,0) NOT NULL ENABLE, 
	OUTCOME NUMBER, 
	ERROR_CODE VARCHAR2(5 CHAR), 
	MESSAGE VARCHAR2(100 CHAR), 
	CORRELATION_ID VARCHAR2(50 CHAR), 
	ID_PAGOPA NUMBER, 
	CLIENT_GUID VARCHAR2(40 CHAR), 
	IS_PROCESSED NUMBER, 
	MDC_INFO VARCHAR2(500 CHAR)
 ) SEGMENT CREATION IMMEDIATE 
 PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
NOCOMPRESS LOGGING
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 TABLESPACE AGID_DATA;
CREATE UNIQUE INDEX BPAY_CORRELATION_ID_IDX ON PP_BPAY_PAYMENT_RESPONSE (CORRELATION_ID) 
 PCTFREE 10 INITRANS 2 MAXTRANS 255 
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 TABLESPACE AGID_DATA PARALLEL 1;
 ALTER INDEX BPAY_CORRELATION_ID_IDX NOPARALLEL;
CREATE UNIQUE INDEX BPAY_ID_PAGOPA_IDX ON PP_BPAY_PAYMENT_RESPONSE (ID_PAGOPA) 
 PCTFREE 10 INITRANS 2 MAXTRANS 255 
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 TABLESPACE AGID_DATA PARALLEL 1;
 ALTER INDEX BPAY_ID_PAGOPA_IDX NOPARALLEL;
ALTER TABLE PP_BPAY_PAYMENT_RESPONSE ADD CONSTRAINT PK_BPAY_PAYMENT_RESPONSE PRIMARY KEY (ID)
 USING INDEX (CREATE UNIQUE INDEX PK_BPAY_PAYMENT_RESPONSE ON PP_BPAY_PAYMENT_RESPONSE (ID) 
 PCTFREE 10 INITRANS 2 MAXTRANS 255 
 STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
 PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
 TABLESPACE AGID_DATA ) ENABLE;
ALTER INDEX BPAY_ID_PAGOPA_IDX NOPARALLEL;