CREATE TABLE PP_PGS_REQUEST_INFO (
  ID                NUMBER(9, 0) CONSTRAINT PGS_REQUEST_INFO_ID_NOT_NULL NOT NULL,
  ENDPOINT          VARCHAR2(50 CHAR),
  GUID              VARCHAR2(40 CHAR),
  CLIENT_ID         VARCHAR2(150 CHAR),
  ID_TRANSACTION    NUMBER,
  CORRELATION_ID    VARCHAR2(50 CHAR),
  AUTH_OUTCOME      NUMBER,
  AUTH_URL          VARCHAR2(50 CHAR),
  AUTH_CODE         VARCHAR2(50 CHAR),
  REQUEST           VARCHAR2(500 CHAR),
  RESOURCE_PATH     VARCHAR2(150 CHAR),
  IS_PROCESSED      NUMBER,
  MDC_INFO          VARCHAR2(500 CHAR),
  ERROR_CODE        VARCHAR2(50 CHAR),
  CONSTRAINT PK_PGS_REQUEST_INFO PRIMARY KEY (ID)
);

CREATE UNIQUE INDEX PGS_REQUEST_GUID_IDX ON PP_PGS_REQUEST_INFO (GUID);
CREATE UNIQUE INDEX PGS_REQUEST_CORRELATION_ID_IDX ON PP_PGS_REQUEST_INFO (CORRELATION_ID);
CREATE UNIQUE INDEX PGS_REQUEST_ID_TRANSACTION_IDX ON PP_PGS_REQUEST_INFO (ID_TRANSACTION);

CREATE SEQUENCE SEQ_PGS_REQUEST_INFO
START WITH 1
INCREMENT BY 1
NOCACHE;