-- create new temporary VARCHAR2 column
ALTER TABLE PP_PGS_REQUEST_INFO ADD ID_TRANSACTION_NEW VARCHAR2(50);

-- copy values from ID_TRANSACTION to ID_TRANSACTION_NEW
UPDATE PP_PGS_REQUEST_INFOSET ID_TRANSACTION_NEW = TO_CHAR(ID_TRANSACTION);

-- drop old column ID_TRANSACTION
ALTER TABLE PP_PGS_REQUEST_INFO DROP COLUMN ID_TRANSACTION;

-- rename new column ID_TRANSACTION_NEW to ID_TRANSACTION
ALTER TABLE PP_PGS_REQUEST_INFO RENAME COLUMN ID_TRANSACTION_NEW TO ID_TRANSACTION;