ALTER TABLE PP_PGS_REQUEST_INFO ADD "ID_TRANSACTION_1" VARCHAR(50);
UPDATE PP_PGS_REQUEST_INFO
SET "ID_TRANSACTION_1" = "ID_TRANSACTION";
ALTER TABLE PP_PGS_REQUEST_INFO DROP COLUMN "ID_TRANSACTION";
ALTER TABLE PP_PGS_REQUEST_INFO RENAME COLUMN "ID_TRANSACTION_1" TO "ID_TRANSACTION";
