CREATE TABLE PP_PGS_CONFIG
(
    "ID_CONFIG" NUMBER(*,0) NOT NULL ENABLE,
	"CONFIG_KEY" VARCHAR2(128),
	"CONFIG_VALUE" CLOB,
	"LAST_UPDATE_DATE" DATE,
	CONSTRAINT "CONFIG_KEY_UQ" UNIQUE ("CONFIG_KEY")
);

CREATE SEQUENCE SEQ_PGS_CONFIG
 START WITH 1
 INCREMENT BY 1
 NOCACHE
 NOCYCLE;
