CREATE TABLE PP_PGS_RESPONSE_INFO (
  ID                	NUMBER(9, 0) CONSTRAINT PGS_RESPONSE_INFO_ID_NOT_NULL NOT NULL,
  REQUEST_ID        	VARCHAR2(40 CHAR),
  OPERATION_ID      	VARCHAR2(15 CHAR),
  RESPONSE_TIMESTAMP    TIMESTAMP,
  HTML    				CLOB,
  ERROR_CODE      		VARCHAR2(10),
  ERRORE_MESSAGE		VARCHAR2(50 CHAR),
  MAC		         	VARCHAR2(40 CHAR),
  NONCE		           	VARCHAR2(50 CHAR),
  CONSTRAINT PK_PGS_RESPONSE_INFO PRIMARY KEY (ID),
  CONSTRAINT PP_PGS_REQUEST_INFO_FK FOREIGN KEY (FK_REQUEST_INFO) REFERENCES PP_PGS_REQUEST_INFO (GUID)
);

CREATE SEQUENCE SEQ_PGS_RESPONSE_INFO
START WITH 1
INCREMENT BY 1
NOCACHE;