package it.pagopa.pm.gateway.dto.transaction;

public enum TransactionStatusEnum {
    ACTIVATED,
    AUTHORIZATION_REQUESTED,
    AUTHORIZATION_COMPLETED,
    CLOSED,
    CLOSURE_ERROR,
    NOTIFIED_OK,
    NOTIFIED_KO,
    NOTIFICATION_ERROR,
    NOTIFICATION_REQUESTED,
    EXPIRED,
    REFUNDED,
    CANCELED,
    EXPIRED_NOT_AUTHORIZED,
    UNAUTHORIZED,
    REFUND_ERROR,
    REFUND_REQUESTED,
    CANCELLATION_REQUESTED,
    CANCELLATION_EXPIRED
}
